language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
before_install:
  - pip install codecov
install:
  - pip install Pillow
script:
  - coverage run --include=common.py,data.py,CLI.py,Color.py -m unittest tests/test_*.py
after_success:
  - codecov
