language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
install:
  - pip install -r requirements.txt
  - pip install black codecov
script:
  - python -m black -l 120 --check color_wallpaper/
  - coverage run --include=color_wallpaper/*.py -m unittest tests/test_*.py
after_success:
  - codecov
