from PIL import Image
from typing import Dict, List

__all__ = ['pretty_names', 'hex_to_color', 'color_to_hex', 'font']

pretty_names = {
    'aliceblue': 'Alice Blue',
    'antiquewhite': 'Antique White',
    'blanchedalmond': 'Blanched Almond',
    'blueviolet': 'Blue Violet',
    'cadetblue': 'Cadet Blue',
    'cornflowerblue': 'Cornflower Blue',
    'darkgoldenrod': 'Dark Goldenrod',
    'darkgrey': 'Dark Grey',
    'darkgreen': 'Dark Green',
    'darkkhaki': 'Dark Khaki',
    'darkmagenta': 'Dark Magenta',
    'darkolivegreen': 'Dark Olive Green',
    'darkorange': 'Dark Orange',
    'darkorchid': 'Dark Orchid',
    'darkred': 'Dark Red',
    'darksalmon': 'Dark Salmon',
    'darkseagreen': 'Dark Sea Green',
    'darkslateblue': 'Dark Slate Blue',
    'darkslategrey': 'Dark Slategrey',
    'darkturquoise': 'Dark Turquoise',
    'darkviolet': 'Dark Violet',
    'deeppink': 'Deep Pink',
    'deepskyblue': 'Deep Sky Blue',
    'dimgrey': 'Dim Grey',
    'dodgerblue': 'Dodger Blue',
    'firebrick': 'Fire Brick',
    'floralwhite': 'Floral White',
    'forestgreen': 'Forest Green',
    'ghostwhite': 'Ghost White',
    'greenyellow': 'Green Yellow',
    'indianred': 'Indian Red',
    'lavenderblush': 'Lavender Blush',
    'lawngreen': 'Lawn Green',
    'lemonchiffon': 'Lemon Chiffon',
    'lightblue': 'Light Blue',
    'lightcoral': 'Light Coral',
    'lightcyan': 'Light Cyan',
    'lightgoldenrodyellow': 'Light Goldenrod Yellow',
    'lightgrey': 'Light Grey',
    'lightgreen': 'Light Green',
    'lightpink': 'Light Pink',
    'lightsalmon': 'Light Salmon',
    'lightseagreen': 'Light Sea Green',
    'lightskyblue': 'Light Sky Blue',
    'lightslategrey': 'Light Slategrey',
    'lightsteelblue': 'Light Steelblue',
    'lightyellow': 'Light Yellow',
    'limegreen': 'Lime Green',
    'mediumaquamarine': 'Medium Aquamarine',
    'mediumblue': 'Medium Blue',
    'mediumorchid': 'Medium Orchid',
    'mediumpurple': 'Medium Purple',
    'mediumseagreen': 'Medium Sea Green',
    'mediumslateblue': 'Medium Slate Blue',
    'mediumspringgreen': 'Medium Spring Green',
    'mediumturquoise': 'Medium Turquoise',
    'mediumvioletred': 'Medium Violet Red',
    'midnightblue': 'Midnight Blue',
    'mintcream': 'Mint Cream',
    'mistyrose': 'Misty Rose',
    'navajowhite': 'Navajo White',
    'oldlace': 'Old Lace',
    'olivedrab': 'Olive Drab',
    'orangered': 'Orange Red',
    'palegoldenrod': 'Pale Golden Rod',
    'palegreen': 'Pale Green',
    'paleturquoise': 'Pale Turquoise',
    'palevioletred': 'Pale Violet Red',
    'papayawhip': 'Papaya Whip',
    'peachpuff': 'Peach Puff',
    'powderblue': 'Powder Blue',
    'rosybrown': 'Rosy Brown',
    'royalblue': 'Royal Blue',
    'saddlebrown': 'Saddle Brown',
    'sandybrown': 'Sandy Brown',
    'seagreen': 'Sea Green',
    'seashell': 'Sea Shell',
    'skyblue': 'Sky Blue',
    'slateblue': 'Slate Blue',
    'slategrey': 'Slate Grey',
    'springgreen': 'Spring Green',
    'steelblue': 'Steel Blue',
    'whitesmoke': 'White Smoke',
    'yellowgreen': 'Yellow Green',
    'cloudyblue': 'Cloudy Blue',
    'darkpastelgreen': 'Dark Pastel Green',
    'electriclime': 'Electric Lime',
    'freshgreen': 'Fresh Green',
    'lighteggplant': 'Light Eggplant',
    'nastygreen': 'Nasty Green',
    'reallylightblue': 'Really Light Blue',
    'warmpurple': 'Warm Purple',
    'yellowishtan': 'Yellowish Tan',
    'darkgrassgreen': 'Dark Grass Green',
    'dustyteal': 'Dusty Teal',
    'greyteal': 'Grey Teal',
    'macaroniandcheese': 'Macaroni And Cheese',
    'pinkishtan': 'Pinkish Tan',
    'strongblue': 'Strong Blue',
    'toxicgreen': 'Toxic Green',
    'windowsblue': 'Windows Blue',
    'blueblue': 'Blue Blue',
    'bluewithahintofpurple': 'Blue With A Hint Of Purple',
    'brightseagreen': 'Bright Sea Green',
    'darkgreenblue': 'Dark Green Blue',
    'deepturquoise': 'Deep Turquoise',
    'greenteal': 'Green Teal',
    'strongpink': 'Strong Pink',
    'deepaqua': 'Deep Aqua',
    'lavenderpink': 'Lavender Pink',
    'lightmossgreen': 'Light Moss Green',
    'lightseafoamgreen': 'Light Seafoam Green',
    'oliveyellow': 'Olive Yellow',
    'pigpink': 'Pig Pink',
    'deeplilac': 'Deep Lilac',
    'dustylavender': 'Dusty Lavender',
    'purpleygrey': 'Purpley Grey',
    'candypink': 'Candy Pink',
    'lightpastelgreen': 'Light Pastel Green',
    'boringgreen': 'Boring Green',
    'kiwigreen': 'Kiwi Green',
    'lightgreygreen': 'Light Grey Green',
    'orangepink': 'Orange Pink',
    'teagreen': 'Tea Green',
    'verylightbrown': 'Very Light Brown',
    'eggshell': 'Egg Shell',
    'eggplantpurple': 'Eggplant Purple',
    'powderpink': 'Powder Pink',
    'reddishgrey': 'Reddish Grey',
    'babyshitbrown': 'Baby Shit Brown',
    'stormyblue': 'Stormy Blue',
    'uglybrown': 'Ugly Brown',
    'darkishpink': 'Darkish Pink',
    'deepbrown': 'Deep Brown',
    'greenishbeige': 'Greenish Beige',
    'offblue': 'Off Blue',
    'battleshipgrey': 'Battleship Grey',
    'brownygreen': 'Browny Green',
    'kelleygreen': 'Kelley Green',
    'sicklyyellow': 'Sickly Yellow',
    'sunnyyellow': 'Sunny Yellow',
    'lightlightgreen': 'Light Light Green',
    'palegold': 'Pale Gold',
    'sunyellow': 'Sun Yellow',
    'tangreen': 'Tan Green',
    'darkcream': 'Dark Cream',
    'lightlavendar': 'Light Lavendar',
    'poisongreen': 'Poison Green',
    'babypukegreen': 'Baby Puke Green',
    'brightyellowgreen': 'Bright Yellow Green',
    'charcoalgrey': 'Charcoal Grey',
    'lightpeagreen': 'Light Pea Green',
    'radioactivegreen': 'Radioactive Green',
    'rawsienna': 'Raw Sienna',
    'babypurple': 'Baby Purple',
    'lightroyalblue': 'Light Royal Blue',
    'rustbrown': 'Rust Brown',
    'sandbrown': 'Sand Brown',
    'tealishgreen': 'Tealish Green',
    'burntsiena': 'Burnt Siena',
    'duskblue': 'Dusk Blue',
    'oldrose': 'Old Rose',
    'palelightgreen': 'Pale Light Green',
    'peachypink': 'Peachy Pink',
    'rosypink': 'Rosy Pink',
    'lightbluishgreen': 'Light Bluish Green',
    'lightbrightgreen': 'Light Bright Green',
    'lightneongreen': 'Light Neon Green',
    'lightseafoam': 'Light Seafoam',
    'tiffanyblue': 'Tiffany Blue',
    'washedoutgreen': 'Washed Out Green',
    'brownyorange': 'Browny Orange',
    'niceblue': 'Nice Blue',
    'greyishteal': 'Greyish Teal',
    'orangeyyellow': 'Orangey Yellow',
    'verydarkbrown': 'Very Dark Brown',
    'uglyblue': 'Ugly Blue',
    'clearblue': 'Clear Blue',
    'foamgreen': 'Foam Green',
    'lightgold': 'Light Gold',
    'seafoamblue': 'Seafoam Blue',
    'violetpink': 'Violet Pink',
    'yellowtan': 'Yellow Tan',
    'darkfuchsia': 'Dark Fuchsia',
    'indigoblue': 'Indigo Blue',
    'lightyellowishgreen': 'Light Yellowish Green',
    'palemagenta': 'Pale Magenta',
    'richpurple': 'Rich Purple',
    'sunfloweryellow': 'Sunflower Yellow',
    'racinggreen': 'Racing Green',
    'vividpurple': 'Vivid Purple',
    'darkroyalblue': 'Dark Royal Blue',
    'mutedpink': 'Muted Pink',
    'boogergreen': 'Booger Green',
    'coolgrey': 'Cool Grey',
    'darktaupe': 'Dark Taupe',
    'darkishpurple': 'Darkish Purple',
    'truegreen': 'True Green',
    'coralpink': 'Coral Pink',
    'darksage': 'Dark Sage',
    'flatblue': 'Flat Blue',
    'richblue': 'Rich Blue',
    'dirtypurple': 'Dirty Purple',
    'ickygreen': 'Icky Green',
    'lightkhaki': 'Light Khaki',
    'warmblue': 'Warm Blue',
    'darkhotpink': 'Dark Hot Pink',
    'deepseablue': 'Deep Sea Blue',
    'darkyellowgreen': 'Dark Yellow Green',
    'palepeach': 'Pale Peach',
    'plumpurple': 'Plum Purple',
    'goldenrod': 'Golden Rod',
    'neonred': 'Neon Red',
    'oldpink': 'Old Pink',
    'verypaleblue': 'Very Pale Blue',
    'bloodorange': 'Blood Orange',
    'sandyellow': 'Sand Yellow',
    'claybrown': 'Clay Brown',
    'darkbluegrey': 'Dark Blue Grey',
    'flatgreen': 'Flat Green',
    'lightgreenblue': 'Light Green Blue',
    'warmpink': 'Warm Pink',
    'grossgreen': 'Gross Green',
    'metallicblue': 'Metallic Blue',
    'palesalmon': 'Pale Salmon',
    'sapgreen': 'Sap Green',
    'blueygrey': 'Bluey Grey',
    'greenygrey': 'Greeny Grey',
    'highlightergreen': 'Highlighter Green',
    'lightlightblue': 'Light Light Blue',
    'lightmint': 'Light Mint',
    'rawumber': 'Raw Umber',
    'vividblue': 'Vivid Blue',
    'deeplavender': 'Deep Lavender',
    'dullteal': 'Dull Teal',
    'lightgreenishblue': 'Light Greenish Blue',
    'mudgreen': 'Mud Green',
    'redwine': 'Red Wine',
    'shitgreen': 'Shit Green',
    'tanbrown': 'Tan Brown',
    'palemauve': 'Pale Mauve',
    'poopgreen': 'Poop Green',
    'greenishturquoise': 'Greenish Turquoise',
    'pastelred': 'Pastel Red',
    'pissyellow': 'Piss Yellow',
    'brightcyan': 'Bright Cyan',
    'darkcoral': 'Dark Coral',
    'algaegreen': 'Algae Green',
    'darkishred': 'Darkish Red',
    'reddybrown': 'Reddy Brown',
    'blushpink': 'Blush Pink',
    'camouflagegreen': 'Camouflage Green',
    'vibrantblue': 'Vibrant Blue',
    'darksand': 'Dark Sand',
    'warmbrown': 'Warm Brown',
    'bubblegumpink': 'Bubblegum Pink',
    'duckeggblue': 'Duck Egg Blue',
    'greenishcyan': 'Greenish Cyan',
    'dustyorange': 'Dusty Orange',
    'offyellow': 'Off Yellow',
    'paleolivegreen': 'Pale Olive Green',
    'lightbluegrey': 'Light Blue Grey',
    'driedblood': 'Dried Blood',
    'lightishpurple': 'Lightish Purple',
    'rustyred': 'Rusty Red',
    'lavenderblue': 'Lavender Blue',
    'lightgrassgreen': 'Light Grass Green',
    'lightmintgreen': 'Light Mint Green',
    'brickorange': 'Brick Orange',
    'lightishred': 'Lightish Red',
    'pureblue': 'Pure Blue',
    'twilightblue': 'Twilight Blue',
    'violetred': 'Violet Red',
    'yellowybrown': 'Yellowy Brown',
    'muddyyellow': 'Muddy Yellow',
    'darkseafoamgreen': 'Dark Seafoam Green',
    'deeprose': 'Deep Rose',
    'dustyred': 'Dusty Red',
    'lemonlime': 'Lemon Lime',
    'brownyellow': 'Brown Yellow',
    'purplebrown': 'Purple Brown',
    'bananayellow': 'Banana Yellow',
    'lipstickred': 'Lipstick Red',
    'waterblue': 'Water Blue',
    'browngrey': 'Brown Grey',
    'vibrantpurple': 'Vibrant Purple',
    'babygreen': 'Baby Green',
    'barfgreen': 'Barf Green',
    'eggshellblue': 'Eggshell Blue',
    'sandyyellow': 'Sandy Yellow',
    'coolgreen': 'Cool Green',
    'hotmagenta': 'Hot Magenta',
    'babyshitgreen': 'Baby Shit Green',
    'brownishpink': 'Brownish Pink',
    'darkaquamarine': 'Dark Aquamarine',
    'lightmustard': 'Light Mustard',
    'paleskyblue': 'Pale Sky Blue',
    'turtlegreen': 'Turtle Green',
    'brightolive': 'Bright Olive',
    'darkgreyblue': 'Dark Grey Blue',
    'greenybrown': 'Greeny Brown',
    'lemongreen': 'Lemon Green',
    'lightperiwinkle': 'Light Periwinkle',
    'seaweedgreen': 'Seaweed Green',
    'sunshineyellow': 'Sunshine Yellow',
    'uglypurple': 'Ugly Purple',
    'mediumpink': 'Medium Pink',
    'pukebrown': 'Puke Brown',
    'verylightpink': 'Very Light Pink',
    'fadedyellow': 'Faded Yellow',
    'verypalegreen': 'Very Pale Green',
    'vibrantgreen': 'Vibrant Green',
    'brightlime': 'Bright Lime',
    'lightaquamarine': 'Light Aquamarine',
    'lightsage': 'Light Sage',
    'babypoo': 'Baby Poo',
    'darkseafoam': 'Dark Seafoam',
    'deepteal': 'Deep Teal',
    'rustorange': 'Rust Orange',
    'dirtyblue': 'Dirty Blue',
    'ferngreen': 'Fern Green',
    'brightlilac': 'Bright Lilac',
    'weirdgreen': 'Weird Green',
    'peacockblue': 'Peacock Blue',
    'avocadogreen': 'Avocado Green',
    'fadedorange': 'Faded Orange',
    'grapepurple': 'Grape Purple',
    'hotgreen': 'Hot Green',
    'limeyellow': 'Lime Yellow',
    'purplishbrown': 'Purplish Brown',
    'vomityellow': 'Vomit Yellow',
    'palecyan': 'Pale Cyan',
    'keylime': 'Key Lime',
    'tomatored': 'Tomato Red',
    'nightblue': 'Night Blue',
    'purpleishpink': 'Purpleish Pink',
    'babypoopgreen': 'Baby Poop Green',
    'greenapple': 'Green Apple',
    'almostblack': 'Almost Black',
    'coolblue': 'Cool Blue',
    'leafygreen': 'Leafy Green',
    'mustardbrown': 'Mustard Brown',
    'dullbrown': 'Dull Brown',
    'froggreen': 'Frog Green',
    'vividgreen': 'Vivid Green',
    'brightlightgreen': 'Bright Light Green',
    'flurogreen': 'Fluro Green',
    'navygreen': 'Navy Green',
    'ultramarineblue': 'Ultramarine Blue',
    'pastelorange': 'Pastel Orange',
    'yellowishorange': 'Yellowish Orange',
    'darkplum': 'Dark Plum',
    'pinkishorange': 'Pinkish Orange',
    'midnightpurple': 'Midnight Purple',
    'lighturple': 'Light Urple',
    'darkmint': 'Dark Mint',
    'greenishtan': 'Greenish Tan',
    'lightburgundy': 'Light Burgundy',
    'turquoiseblue': 'Turquoise Blue',
    'uglypink': 'Ugly Pink',
    'electricpink': 'Electric Pink',
    'mutedpurple': 'Muted Purple',
    'midgreen': 'Mid Green',
    'neonyellow': 'Neon Yellow',
    'carnationpink': 'Carnation Pink',
    'muddybrown': 'Muddy Brown',
    'turquoisegreen': 'Turquoise Green',
    'mutedblue': 'Muted Blue',
    'palerose': 'Pale Rose',
    'darkmintgreen': 'Dark Mint Green',
    'sickgreen': 'Sick Green',
    'rustyorange': 'Rusty Orange',
    'rosered': 'Rose Red',
    'paleaqua': 'Pale Aqua',
    'deeporange': 'Deep Orange',
    'mossygreen': 'Mossy Green',
    'grassygreen': 'Grassy Green',
    'palelimegreen': 'Pale Lime Green',
    'lightgreyblue': 'Light Grey Blue',
    'palegrey': 'Pale Grey',
    'purplered': 'Purple Red',
    'palelime': 'Pale Lime',
    'greenishteal': 'Greenish Teal',
    'deepmagenta': 'Deep Magenta',
    'lightpeach': 'Light Peach',
    'milkchocolate': 'Milk Chocolate',
    'offgreen': 'Off Green',
    'purplypink': 'Purply Pink',
    'duskyblue': 'Dusky Blue',
    'lightbeige': 'Light Beige',
    'butteryellow': 'Butter Yellow',
    'duskypurple': 'Dusky Purple',
    'frenchblue': 'French Blue',
    'uglyyellow': 'Ugly Yellow',
    'greenyyellow': 'Greeny Yellow',
    'orangishred': 'Orangish Red',
    'shamrockgreen': 'Shamrock Green',
    'orangishbrown': 'Orangish Brown',
    'treegreen': 'Tree Green',
    'deepviolet': 'Deep Violet',
    'warmgrey': 'Warm Grey',
    'darkindigo': 'Dark Indigo',
    'blueygreen': 'Bluey Green',
    'greypink': 'Grey Pink',
    'softpurple': 'Soft Purple',
    'brownred': 'Brown Red',
    'mediumgrey': 'Medium Grey',
    'purpleypink': 'Purpley Pink',
    'easterpurple': 'Easter Purple',
    'lightyellowgreen': 'Light Yellow Green',
    'darknavyblue': 'Dark Navy Blue',
    'lightrose': 'Light Rose',
    'purplishred': 'Purplish Red',
    'slimegreen': 'Slime Green',
    'babypoop': 'Baby Poop',
    'irishgreen': 'Irish Green',
    'darknavy': 'Dark Navy',
    'greenyblue': 'Greeny Blue',
    'lightplum': 'Light Plum',
    'pinkishgrey': 'Pinkish Grey',
    'dirtyorange': 'Dirty Orange',
    'rustred': 'Rust Red',
    'palelilac': 'Pale Lilac',
    'orangeyred': 'Orangey Red',
    'primaryblue': 'Primary Blue',
    'kermitgreen': 'Kermit Green',
    'brownishpurple': 'Brownish Purple',
    'murkygreen': 'Murky Green',
    'verydarkpurple': 'Very Dark Purple',
    'bottlegreen': 'Bottle Green',
    'fireenginered': 'Fire Engine Red',
    'yellowochre': 'Yellow Ochre',
    'pumpkinorange': 'Pumpkin Orange',
    'paleolive': 'Pale Olive',
    'lightlilac': 'Light Lilac',
    'lightishgreen': 'Lightish Green',
    'carolinablue': 'Carolina Blue',
    'shockingpink': 'Shocking Pink',
    'brightlimegreen': 'Bright Lime Green',
    'pinkishbrown': 'Pinkish Brown',
    'poobrown': 'Poo Brown',
    'brightskyblue': 'Bright Sky Blue',
    'dirtbrown': 'Dirt Brown',
    'darklime': 'Dark Lime',
    'mediumbrown': 'Medium Brown',
    'mutedgreen': 'Muted Green',
    "robin'segg": "Robin's Egg",
    'brightaqua': 'Bright Aqua',
    'brightlavender': 'Bright Lavender',
    'verylightpurple': 'Very Light Purple',
    'lightnavy': 'Light Navy',
    'pinkred': 'Pink Red',
    'olivebrown': 'Olive Brown',
    'poopbrown': 'Poop Brown',
    'mustardgreen': 'Mustard Green',
    'oceangreen': 'Ocean Green',
    'verydarkblue': 'Very Dark Blue',
    'dustygreen': 'Dusty Green',
    'lightnavyblue': 'Light Navy Blue',
    'mintygreen': 'Minty Green',
    'jadegreen': 'Jade Green',
    'brightlightblue': 'Bright Light Blue',
    'lightlime': 'Light Lime',
    'orangeyellow': 'Orange Yellow',
    'fadedpink': 'Faded Pink',
    'britishracinggreen': 'British Racing Green',
    'mudbrown': 'Mud Brown',
    'robineggblue': 'Robin Egg Blue',
    'aquamarine': 'Aqua Marine',
    'softpink': 'Soft Pink',
    'orangeybrown': 'Orangey Brown',
    'cherryred': 'Cherry Red',
    'burntyellow': 'Burnt Yellow',
    'brownishgrey': 'Brownish Grey',
    'purplishgrey': 'Purplish Grey',
    'greyishpink': 'Greyish Pink',
    'pastelyellow': 'Pastel Yellow',
    'blueypurple': 'Bluey Purple',
    'canaryyellow': 'Canary Yellow',
    'fadedred': 'Faded Red',
    'brightmagenta': 'Bright Magenta',
    'darkishgreen': 'Darkish Green',
    'brownorange': 'Brown Orange',
    'duskyrose': 'Dusky Rose',
    'sicklygreen': 'Sickly Green',
    'purplyblue': 'Purply Blue',
    'purpleishblue': 'Purpleish Blue',
    'hospitalgreen': 'Hospital Green',
    'shitbrown': 'Shit Brown',
    'midblue': 'Mid Blue',
    'eastergreen': 'Easter Green',
    'softblue': 'Soft Blue',
    'ceruleanblue': 'Cerulean Blue',
    'goldenbrown': 'Golden Brown',
    'brightturquoise': 'Bright Turquoise',
    'redpink': 'Red Pink',
    'redpurple': 'Red Purple',
    'greyishbrown': 'Greyish Brown',
    'steelgrey': 'Steel Grey',
    'lighterpurple': 'Lighter Purple',
    'brightviolet': 'Bright Violet',
    'prussianblue': 'Prussian Blue',
    'slategreen': 'Slate Green',
    'dirtypink': 'Dirty Pink',
    'darkbluegreen': 'Dark Blue Green',
    'yellowygreen': 'Yellowy Green',
    'darkgold': 'Dark Gold',
    'darkishblue': 'Darkish Blue',
    'dullred': 'Dull Red',
    'pinkyred': 'Pinky Red',
    'paleteal': 'Pale Teal',
    'militarygreen': 'Military Green',
    'barbiepink': 'Barbie Pink',
    'peasoupgreen': 'Pea Soup Green',
    'darkmustard': 'Dark Mustard',
    'verydarkgreen': 'Very Dark Green',
    'duskypink': 'Dusky Pink',
    'redviolet': 'Red Violet',
    'lemonyellow': 'Lemon Yellow',
    'dullyellow': 'Dull Yellow',
    'darklimegreen': 'Dark Lime Green',
    'denimblue': 'Denim Blue',
    'tealblue': 'Teal Blue',
    'lightishblue': 'Lightish Blue',
    'purpleyblue': 'Purpley Blue',
    'lightindigo': 'Light Indigo',
    'swampgreen': 'Swamp Green',
    'browngreen': 'Brown Green',
    'darkmaroon': 'Dark Maroon',
    'hotpurple': 'Hot Purple',
    'darkforestgreen': 'Dark Forest Green',
    'fadedblue': 'Faded Blue',
    'drabgreen': 'Drab Green',
    'lightlimegreen': 'Light Lime Green',
    'snotgreen': 'Snot Green',
    'lightbluegreen': 'Light Blue Green',
    'lightmauve': 'Light Mauve',
    'muddygreen': 'Muddy Green',
    'dullorange': 'Dull Orange',
    'electricpurple': 'Electric Purple',
    'fluorescentgreen': 'Fluorescent Green',
    'yellowishbrown': 'Yellowish Brown',
    'softgreen': 'Soft Green',
    'brightorange': 'Bright Orange',
    'purplegrey': 'Purple Grey',
    'acidgreen': 'Acid Green',
    'palelavender': 'Pale Lavender',
    'violetblue': 'Violet Blue',
    'lightforestgreen': 'Light Forest Green',
    'burntred': 'Burnt Red',
    'khakigreen': 'Khaki Green',
    'fadedpurple': 'Faded Purple',
    'greybrown': 'Grey Brown',
    'greengrey': 'Green Grey',
    'trueblue': 'True Blue',
    'paleviolet': 'Pale Violet',
    'periwinkleblue': 'Periwinkle Blue',
    'greenbrown': 'Green Brown',
    'brightteal': 'Bright Teal',
    'brownishyellow': 'Brownish Yellow',
    'peasoup': 'Pea Soup',
    'barneypurple': 'Barney Purple',
    'pukeyellow': 'Puke Yellow',
    'bluishgrey': 'Bluish Grey',
    'darkperiwinkle': 'Dark Periwinkle',
    'darklilac': 'Dark Lilac',
    'lightmaroon': 'Light Maroon',
    'dustypurple': 'Dusty Purple',
    'terracotta': 'Terra Cotta',
    'marineblue': 'Marine Blue',
    'tealgreen': 'Teal Green',
    'lightergreen': 'Lighter Green',
    'electricgreen': 'Electric Green',
    'dustyblue': 'Dusty Blue',
    'goldenyellow': 'Golden Yellow',
    'brightyellow': 'Bright Yellow',
    'lightlavender': 'Light Lavender',
    'darkpeach': 'Dark Peach',
    'junglegreen': 'Jungle Green',
    'yellowbrown': 'Yellow Brown',
    'dullpurple': 'Dull Purple',
    'chocolatebrown': 'Chocolate Brown',
    'winered': 'Wine Red',
    'neonblue': 'Neon Blue',
    'dirtygreen': 'Dirty Green',
    'lighttan': 'Light Tan',
    'iceblue': 'Ice Blue',
    'darkmauve': 'Dark Mauve',
    'verylightblue': 'Very Light Blue',
    'greypurple': 'Grey Purple',
    'pastelpink': 'Pastel Pink',
    'verylightgreen': 'Very Light Green',
    'darkskyblue': 'Dark Sky Blue',
    'dullpink': 'Dull Pink',
    'reddishorange': 'Reddish Orange',
    'deepgreen': 'Deep Green',
    'vomitgreen': 'Vomit Green',
    'purplepink': 'Purple Pink',
    'dustypink': 'Dusty Pink',
    'fadedgreen': 'Faded Green',
    'camogreen': 'Camo Green',
    'pinkypurple': 'Pinky Purple',
    'pinkpurple': 'Pink Purple',
    'brownishred': 'Brownish Red',
    'darkrose': 'Dark Rose',
    'emeraldgreen': 'Emerald Green',
    'palebrown': 'Pale Brown',
    'dullblue': 'Dull Blue',
    'burntumber': 'Burnt Umber',
    'mediumgreen': 'Medium Green',
    'lightaqua': 'Light Aqua',
    'lightolivegreen': 'Light Olive Green',
    'brownishorange': 'Brownish Orange',
    'darkaqua': 'Dark Aqua',
    'purplishpink': 'Purplish Pink',
    'greenishgrey': 'Greenish Grey',
    'uglygreen': 'Ugly Green',
    'darkbeige': 'Dark Beige',
    'palered': 'Pale Red',
    'lightmagenta': 'Light Magenta',
    'yelloworange': 'Yellow Orange',
    'reddishpurple': 'Reddish Purple',
    'reddishpink': 'Reddish Pink',
    'dirtyyellow': 'Dirty Yellow',
    'deepred': 'Deep Red',
    'orangebrown': 'Orange Brown',
    'cobaltblue': 'Cobalt Blue',
    'neonpink': 'Neon Pink',
    'rosepink': 'Rose Pink',
    'greyishpurple': 'Greyish Purple',
    'aquagreen': 'Aqua Green',
    'salmonpink': 'Salmon Pink',
    'brownishgreen': 'Brownish Green',
    'redbrown': 'Red Brown',
    'greenishbrown': 'Greenish Brown',
    'pinegreen': 'Pine Green',
    'babypink': 'Baby Pink',
    'greyishgreen': 'Greyish Green',
    'darkolive': 'Dark Olive',
    'pastelpurple': 'Pastel Purple',
    'aquablue': 'Aqua Blue',
    'sagegreen': 'Sage Green',
    'bloodred': 'Blood Red',
    'pastelblue': 'Pastel Blue',
    'bluishgreen': 'Bluish Green',
    'greenblue': 'Green Blue',
    'darktan': 'Dark Tan',
    'greenishblue': 'Greenish Blue',
    'paleorange': 'Pale Orange',
    'forrestgreen': 'Forrest Green',
    'darklavender': 'Dark Lavender',
    'purpleblue': 'Purple Blue',
    'darkcyan': 'Dark Cyan',
    'neonpurple': 'Neon Purple',
    'lightturquoise': 'Light Turquoise',
    'applegreen': 'Apple Green',
    'dullgreen': 'Dull Green',
    'offwhite': 'Off White',
    'electricblue': 'Electric Blue',
    'bluepurple': 'Blue Purple',
    'brightred': 'Bright Red',
    'pinkishred': 'Pinkish Red',
    'lightolive': 'Light Olive',
    'greyishblue': 'Greyish Blue',
    'purplishblue': 'Purplish Blue',
    'yellowishgreen': 'Yellowish Green',
    'greenishyellow': 'Greenish Yellow',
    'dustyrose': 'Dusty Rose',
    'lightviolet': 'Light Violet',
    'bluishpurple': 'Bluish Purple',
    'redorange': 'Red Orange',
    'oceanblue': 'Ocean Blue',
    'reddishbrown': 'Reddish Brown',
    'burntsienna': 'Burnt Sienna',
    'greygreen': 'Grey Green',
    "robin'seggblue": "Robin's Egg Blue",
    'mossgreen': 'Moss Green',
    'leafgreen': 'Leaf Green',
    'pinkishpurple': 'Pinkish Purple',
    'seablue': 'Sea Blue',
    'palepurple': 'Pale Purple',
    'bluegrey': 'Blue Grey',
    'huntergreen': 'Hunter Green',
    'paleyellow': 'Pale Yellow',
    'mustardyellow': 'Mustard Yellow',
    'lightred': 'Light Red',
    'palepink': 'Pale Pink',
    'deepblue': 'Deep Blue',
    'lightteal': 'Light Teal',
    'darkyellow': 'Dark Yellow',
    'armygreen': 'Army Green',
    'greyblue': 'Grey Blue',
    'pastelgreen': 'Pastel Green',
    'lightorange': 'Light Orange',
    'brightpink': 'Bright Pink',
    'deeppurple': 'Deep Purple',
    'darkbrown': 'Dark Brown',
    'peagreen': 'Pea Green',
    'pukegreen': 'Puke Green',
    'kellygreen': 'Kelly Green',
    'seafoamgreen': 'Seafoam Green',
    'bluegreen': 'Blue Green',
    'darkteal': 'Dark Teal',
    'brickred': 'Brick Red',
    'royalpurple': 'Royal Purple',
    'mintgreen': 'Mint Green',
    'babyblue': 'Baby Blue',
    'brightpurple': 'Bright Purple',
    'paleblue': 'Pale Blue',
    'grassgreen': 'Grass Green',
    'burntorange': 'Burnt Orange',
    'neongreen': 'Neon Green',
    'brightblue': 'Bright Blue',
    'darkpink': 'Dark Pink',
    'olivegreen': 'Olive Green',
    'lightbrown': 'Light Brown',
    'hotpink': 'Hot Pink',
    'navyblue': 'Navy Blue',
    'brightgreen': 'Bright Green',
    'darkpurple': 'Dark Purple',
    'darkblue': 'Dark Blue',
    'lightpurple': 'Light Purple'
}

hex_to_color = {
    'f0f8ff': 'aliceblue',
    'faebd7': 'antiquewhite',
    '00ffff': 'cyan',
    '04d8b2': 'aquamarine',
    '069af3': 'azure',
    'e6daa6': 'beige',
    'ffe4c4': 'bisque',
    '000000': 'black',
    'ffebcd': 'blanchedalmond',
    '0343df': 'blue',
    '5d06e9': 'blueviolet',
    '653700': 'brown',
    'deb887': 'burlywood',
    '4e7496': 'cadetblue',
    'c1f80a': 'chartreuse',
    '3d1c02': 'chocolate',
    'fc5a50': 'coral',
    '5170d7': 'cornflowerblue',
    'fff8dc': 'cornsilk',
    '8c000f': 'crimson',
    '00035b': 'darkblue',
    '0a888a': 'darkcyan',
    'b8860b': 'darkgoldenrod',
    '363737': 'darkgrey',
    '033500': 'darkgreen',
    '9b8f55': 'darkkhaki',
    '960056': 'darkmagenta',
    '3c4d03': 'darkolivegreen',
    'c65102': 'darkorange',
    '9932cc': 'darkorchid',
    '840000': 'darkred',
    'c85a53': 'darksalmon',
    '11875d': 'darkseagreen',
    '214761': 'darkslateblue',
    '2f4f4f': 'darkslategrey',
    '045c5a': 'darkturquoise',
    '34013f': 'darkviolet',
    'cb0162': 'deeppink',
    '0d75f8': 'deepskyblue',
    '696969': 'dimgrey',
    '3e82fc': 'dodgerblue',
    'b22222': 'firebrick',
    'fffaf0': 'floralwhite',
    '06470c': 'forestgreen',
    'c20078': 'magenta',
    'dcdcdc': 'gainsboro',
    'f8f8ff': 'ghostwhite',
    'dbb40c': 'gold',
    'fac205': 'goldenrod',
    '929591': 'grey',
    '15b01a': 'green',
    'c9ff27': 'greenyellow',
    'f0fff0': 'honeydew',
    'ff028d': 'hotpink',
    '850e04': 'indianred',
    '380282': 'indigo',
    'ffffcb': 'ivory',
    'aaa662': 'khaki',
    'c79fef': 'lavender',
    'fff0f5': 'lavenderblush',
    '4da409': 'lawngreen',
    'fffacd': 'lemonchiffon',
    '95d0fc': 'lightblue',
    'f08080': 'lightcoral',
    'acfffc': 'lightcyan',
    'fafad2': 'lightgoldenrodyellow',
    'd8dcd6': 'lightgrey',
    '96f97b': 'lightgreen',
    'ffd1df': 'lightpink',
    'fea993': 'lightsalmon',
    '98f6b0': 'lightseagreen',
    'c6fcff': 'lightskyblue',
    '778899': 'lightslategrey',
    'b0c4de': 'lightsteelblue',
    'fffe7a': 'lightyellow',
    'aaff32': 'lime',
    '89fe05': 'limegreen',
    'faf0e6': 'linen',
    '650021': 'maroon',
    '66cdaa': 'mediumaquamarine',
    '2c6fbb': 'mediumblue',
    'ba55d3': 'mediumorchid',
    '9e43a2': 'mediumpurple',
    '3cb371': 'mediumseagreen',
    '7b68ee': 'mediumslateblue',
    '00fa9a': 'mediumspringgreen',
    '48d1cc': 'mediumturquoise',
    'c71585': 'mediumvioletred',
    '020035': 'midnightblue',
    'f5fffa': 'mintcream',
    'ffe4e1': 'mistyrose',
    'ffe4b5': 'moccasin',
    'ffdead': 'navajowhite',
    '01153e': 'navy',
    'fdf5e6': 'oldlace',
    '6e750e': 'olive',
    '6f7632': 'olivedrab',
    'f97306': 'orange',
    'fd411e': 'orangered',
    'c875c4': 'orchid',
    'eee8aa': 'palegoldenrod',
    'c7fdb5': 'palegreen',
    'a5fbd5': 'paleturquoise',
    'db7093': 'palevioletred',
    'ffefd5': 'papayawhip',
    'ffdab9': 'peachpuff',
    'cd853f': 'peru',
    'ff81c0': 'pink',
    '580f41': 'plum',
    'b1d1fc': 'powderblue',
    '7e1e9c': 'purple',
    '663399': 'rebeccapurple',
    'e50000': 'red',
    'bc8f8f': 'rosybrown',
    '0504aa': 'royalblue',
    '8b4513': 'saddlebrown',
    'ff796c': 'salmon',
    'c4a661': 'sandybrown',
    '53fca1': 'seagreen',
    'fff5ee': 'seashell',
    'a9561e': 'sienna',
    'c5c9c7': 'silver',
    '75bbfd': 'skyblue',
    '5b7c99': 'slateblue',
    '59656d': 'slategrey',
    'fffafa': 'snow',
    'a9f971': 'springgreen',
    '5a7d9a': 'steelblue',
    'd1b26f': 'tan',
    '029386': 'teal',
    'd8bfd8': 'thistle',
    'ef4026': 'tomato',
    '06c2ac': 'turquoise',
    '9a0eea': 'violet',
    'fbdd7e': 'wheat',
    'ffffff': 'white',
    'f5f5f5': 'whitesmoke',
    'ffff14': 'yellow',
    'c0fb2d': 'yellowgreen',
    'acc2d9': 'cloudyblue',
    '56ae57': 'darkpastelgreen',
    'b2996e': 'dust',
    'a8ff04': 'electriclime',
    '69d84f': 'freshgreen',
    '894585': 'lighteggplant',
    '70b23f': 'nastygreen',
    'd4ffff': 'reallylightblue',
    '65ab7c': 'tea',
    '952e8f': 'warmpurple',
    'fcfc81': 'yellowishtan',
    'a5a391': 'cement',
    '388004': 'darkgrassgreen',
    '4c9085': 'dustyteal',
    '5e9b8a': 'greyteal',
    'efb435': 'macaroniandcheese',
    'd99b82': 'pinkishtan',
    '0a5f38': 'spruce',
    '0c06f7': 'strongblue',
    '61de2a': 'toxicgreen',
    '3778bf': 'windowsblue',
    '2242c7': 'blueblue',
    '533cc6': 'bluewithahintofpurple',
    '9bb53c': 'booger',
    '05ffa6': 'brightseagreen',
    '1f6357': 'darkgreenblue',
    '017374': 'deepturquoise',
    '0cb577': 'greenteal',
    'ff0789': 'strongpink',
    'afa88b': 'bland',
    '08787f': 'deepaqua',
    'dd85d7': 'lavenderpink',
    'a6c875': 'lightmossgreen',
    'a7ffb5': 'lightseafoamgreen',
    'c2b709': 'oliveyellow',
    'e78ea5': 'pigpink',
    '966ebd': 'deeplilac',
    'ccad60': 'desert',
    'ac86a8': 'dustylavender',
    '947e94': 'purpleygrey',
    '983fb2': 'purply',
    'ff63e9': 'candypink',
    'b2fba5': 'lightpastelgreen',
    '63b365': 'boringgreen',
    '8ee53f': 'kiwigreen',
    'b7e1a1': 'lightgreygreen',
    'ff6f52': 'orangepink',
    'bdf8a3': 'teagreen',
    'd3b683': 'verylightbrown',
    'ffffd4': 'eggshell',
    '430541': 'eggplantpurple',
    'ffb2d0': 'powderpink',
    '997570': 'reddishgrey',
    'ad900d': 'babyshitbrown',
    'c48efd': 'liliac',
    '507b9c': 'stormyblue',
    '7d7103': 'uglybrown',
    'fffd78': 'custard',
    'da467d': 'darkishpink',
    '410200': 'deepbrown',
    'c9d179': 'greenishbeige',
    'fffa86': 'manilla',
    '5684ae': 'offblue',
    '6b7c85': 'battleshipgrey',
    '6f6c0a': 'brownygreen',
    '7e4071': 'bruise',
    '009337': 'kelleygreen',
    'd0e429': 'sicklyyellow',
    'fff917': 'sunnyyellow',
    '1d5dec': 'azul',
    'b5ce08': 'green/yellow',
    '8fb67b': 'lichen',
    'c8ffb0': 'lightlightgreen',
    'fdde6c': 'palegold',
    'ffdf22': 'sunyellow',
    'a9be70': 'tangreen',
    '6832e3': 'burple',
    'fdb147': 'butterscotch',
    'c7ac7d': 'toupe',
    'fff39a': 'darkcream',
    'efc0fe': 'lightlavendar',
    '40fd14': 'poisongreen',
    'b6c406': 'babypukegreen',
    '9dff00': 'brightyellowgreen',
    '3c4142': 'charcoalgrey',
    'f2ab15': 'squash',
    'ac4f06': 'cinnamon',
    'c4fe82': 'lightpeagreen',
    '2cfa1f': 'radioactivegreen',
    '9a6200': 'rawsienna',
    'ca9bf7': 'babypurple',
    '875f42': 'cocoa',
    '3a2efe': 'lightroyalblue',
    'fd8d49': 'orangeish',
    '8b3103': 'rustbrown',
    'cba560': 'sandbrown',
    '698339': 'swamp',
    '0cdc73': 'tealishgreen',
    'b75203': 'burntsiena',
    '7f8f4e': 'camo',
    '26538d': 'duskblue',
    '63a950': 'fern',
    'c87f89': 'oldrose',
    'b1fc99': 'palelightgreen',
    'ff9a8a': 'peachypink',
    'f6688e': 'rosypink',
    '76fda8': 'lightbluishgreen',
    '53fe5c': 'lightbrightgreen',
    '4efd54': 'lightneongreen',
    'a0febf': 'lightseafoam',
    '7bf2da': 'tiffanyblue',
    'bcf5a6': 'washedoutgreen',
    'ca6b02': 'brownyorange',
    '107ab0': 'niceblue',
    '2138ab': 'sapphire',
    '719f91': 'greyishteal',
    'fdb915': 'orangeyyellow',
    'fefcaf': 'parchment',
    'fcf679': 'straw',
    '1d0200': 'verydarkbrown',
    'cb6843': 'terracota',
    '31668a': 'uglyblue',
    '247afd': 'clearblue',
    'ffffb6': 'creme',
    '90fda9': 'foamgreen',
    '86a17d': 'grey/green',
    'fddc5c': 'lightgold',
    '78d1b6': 'seafoamblue',
    '13bbaf': 'topaz',
    'fb5ffc': 'violetpink',
    '20f986': 'wintergreen',
    'ffe36e': 'yellowtan',
    '9d0759': 'darkfuchsia',
    '3a18b1': 'indigoblue',
    'c2ff89': 'lightyellowishgreen',
    'd767ad': 'palemagenta',
    '720058': 'richpurple',
    'ffda03': 'sunfloweryellow',
    '01c08d': 'green/blue',
    'ac7434': 'leather',
    '014600': 'racinggreen',
    '9900fa': 'vividpurple',
    '02066f': 'darkroyalblue',
    '8e7618': 'hazel',
    'd1768f': 'mutedpink',
    '96b403': 'boogergreen',
    'fdff63': 'canary',
    '95a3a6': 'coolgrey',
    '7f684e': 'darktaupe',
    '751973': 'darkishpurple',
    '089404': 'truegreen',
    'ff6163': 'coralpink',
    '598556': 'darksage',
    '3c73a8': 'flatblue',
    'ba9e88': 'mushroom',
    '021bf9': 'richblue',
    '734a65': 'dirtypurple',
    '06b48b': 'greenblue',
    '8fae22': 'ickygreen',
    'e6f2a2': 'lightkhaki',
    '4b57db': 'warmblue',
    'd90166': 'darkhotpink',
    '015482': 'deepseablue',
    '9d0216': 'carmine',
    '728f02': 'darkyellowgreen',
    'ffe5ad': 'palepeach',
    '4e0550': 'plumpurple',
    'ff073a': 'neonred',
    'c77986': 'oldpink',
    'd6fffe': 'verypaleblue',
    'fe4b03': 'bloodorange',
    'fd5956': 'grapefruit',
    'fce166': 'sandyellow',
    'b2713d': 'claybrown',
    '1f3b4d': 'darkbluegrey',
    '699d4c': 'flatgreen',
    '56fca2': 'lightgreenblue',
    'fb5581': 'warmpink',
    'a0bf16': 'grossgreen',
    'd6fffa': 'ice',
    '4f738e': 'metallicblue',
    'ffb19a': 'palesalmon',
    '5c8b15': 'sapgreen',
    '54ac68': 'algae',
    '89a0b0': 'blueygrey',
    '7ea07a': 'greenygrey',
    '1bfc06': 'highlightergreen',
    'cafffb': 'lightlightblue',
    'b6ffbb': 'lightmint',
    'a75e09': 'rawumber',
    '152eff': 'vividblue',
    '8d5eb7': 'deeplavender',
    '5f9e8f': 'dullteal',
    '63f7b4': 'lightgreenishblue',
    '606602': 'mudgreen',
    'fc86aa': 'pinky',
    '8c0034': 'redwine',
    '758000': 'shitgreen',
    'ab7e4c': 'tanbrown',
    'fe86a4': 'rosa',
    'd5174e': 'lipstick',
    'fed0fc': 'palemauve',
    '680018': 'claret',
    'fedf08': 'dandelion',
    '6f7c00': 'poopgreen',
    'ca0147': 'ruby',
    '1b2431': 'dark',
    '00fbb0': 'greenishturquoise',
    'db5856': 'pastelred',
    'ddd618': 'pissyellow',
    '41fdfe': 'brightcyan',
    'cf524e': 'darkcoral',
    '21c36f': 'algaegreen',
    'a90308': 'darkishred',
    '6e1005': 'reddybrown',
    'fe828c': 'blushpink',
    '4b6113': 'camouflagegreen',
    'beae8a': 'putty',
    '0339f8': 'vibrantblue',
    'a88f59': 'darksand',
    '5d21d0': 'purple/blue',
    'feb209': 'saffron',
    '4e518b': 'twilight',
    '964e02': 'warmbrown',
    '607c8e': 'bluegrey',
    'fe83cc': 'bubblegumpink',
    'c3fbf4': 'duckeggblue',
    '2afeb7': 'greenishcyan',
    '005f6a': 'petrol',
    '0c1793': 'royal',
    'ffff81': 'butter',
    'f0833a': 'dustyorange',
    'f1f33f': 'offyellow',
    'b1d27b': 'paleolivegreen',
    'fc824a': 'orangish',
    '71aa34': 'leaf',
    'b7c9e2': 'lightbluegrey',
    '4b0101': 'driedblood',
    'a552e6': 'lightishpurple',
    'af2f0d': 'rustyred',
    '8b88f8': 'lavenderblue',
    '9af764': 'lightgrassgreen',
    'a6fbb2': 'lightmintgreen',
    'ffc512': 'sunflower',
    '750851': 'velvet',
    'c14a09': 'brickorange',
    'fe2f4a': 'lightishred',
    '0203e2': 'pureblue',
    '0a437a': 'twilightblue',
    'a50055': 'violetred',
    'ae8b0c': 'yellowybrown',
    'fd798f': 'carnation',
    'bfac05': 'muddyyellow',
    '3eaf76': 'darkseafoamgreen',
    'c74767': 'deeprose',
    'b9484e': 'dustyred',
    '647d8e': 'grey/blue',
    'bffe28': 'lemonlime',
    'd725de': 'purple/pink',
    'b29705': 'brownyellow',
    '673a3f': 'purplebrown',
    'a87dc2': 'wisteria',
    'fafe4b': 'bananayellow',
    'c0022f': 'lipstickred',
    '0e87cc': 'waterblue',
    '8d8468': 'browngrey',
    'ad03de': 'vibrantpurple',
    '8cff9e': 'babygreen',
    '94ac02': 'barfgreen',
    'c4fff7': 'eggshellblue',
    'fdee73': 'sandyyellow',
    '33b864': 'coolgreen',
    'fff9d0': 'pale',
    '758da3': 'blue/grey',
    'f504c9': 'hotmagenta',
    '6b8ba4': 'greyblue',
    '8756e4': 'purpley',
    '889717': 'babyshitgreen',
    'c27e79': 'brownishpink',
    '017371': 'darkaquamarine',
    '9f8303': 'diarrhea',
    'f7d560': 'lightmustard',
    'bdf6fe': 'paleskyblue',
    '75b84f': 'turtlegreen',
    '9cbb04': 'brightolive',
    '29465b': 'darkgreyblue',
    '696006': 'greenybrown',
    'adf802': 'lemongreen',
    'c1c6fc': 'lightperiwinkle',
    '35ad6b': 'seaweedgreen',
    'fffd37': 'sunshineyellow',
    'a442a0': 'uglypurple',
    'f36196': 'mediumpink',
    '947706': 'pukebrown',
    'fff4f2': 'verylightpink',
    '1e9167': 'viridian',
    'b5c306': 'bile',
    'feff7f': 'fadedyellow',
    'cffdbc': 'verypalegreen',
    '0add08': 'vibrantgreen',
    '87fd05': 'brightlime',
    '1ef876': 'spearmint',
    '7bfdc7': 'lightaquamarine',
    'bcecac': 'lightsage',
    'ab9004': 'babypoo',
    '1fb57a': 'darkseafoam',
    '00555a': 'deepteal',
    'a484ac': 'heather',
    'c45508': 'rustorange',
    '3f829d': 'dirtyblue',
    '548d44': 'ferngreen',
    'c95efb': 'brightlilac',
    '3ae57f': 'weirdgreen',
    '016795': 'peacockblue',
    '87a922': 'avocadogreen',
    'f0944d': 'fadedorange',
    '5d1451': 'grapepurple',
    '25ff29': 'hotgreen',
    'd0fe1d': 'limeyellow',
    'ffa62b': 'mango',
    '01b44c': 'shamrock',
    'ff6cb5': 'bubblegum',
    '6b4247': 'purplishbrown',
    'c7c10c': 'vomityellow',
    'b7fffa': 'palecyan',
    'aeff6e': 'keylime',
    'ec2d01': 'tomatored',
    '730039': 'merlot',
    '040348': 'nightblue',
    'df4ec8': 'purpleishpink',
    '6ecb3c': 'apple',
    '8f9805': 'babypoopgreen',
    '5edc1f': 'greenapple',
    'd94ff5': 'heliotrope',
    'c8fd3d': 'yellow/green',
    '070d0d': 'almostblack',
    '4984b8': 'coolblue',
    '51b73b': 'leafygreen',
    'ac7e04': 'mustardbrown',
    '4e5481': 'dusk',
    '876e4b': 'dullbrown',
    '58bc08': 'froggreen',
    '2fef10': 'vividgreen',
    '2dfe54': 'brightlightgreen',
    '0aff02': 'flurogreen',
    '9cef43': 'kiwi',
    '18d17b': 'seaweed',
    '35530a': 'navygreen',
    '1805db': 'ultramarineblue',
    '6258c4': 'iris',
    'ff964f': 'pastelorange',
    'ffab0f': 'yellowishorange',
    '8f8ce7': 'perrywinkle',
    '24bca8': 'tealish',
    '3f012c': 'darkplum',
    'cbf85f': 'pear',
    'ff724c': 'pinkishorange',
    '280137': 'midnightpurple',
    'b36ff6': 'lighturple',
    '48c072': 'darkmint',
    'bccb7a': 'greenishtan',
    'a8415b': 'lightburgundy',
    '06b1c4': 'turquoiseblue',
    'cd7584': 'uglypink',
    'f1da7a': 'sandy',
    'ff0490': 'electricpink',
    '805b87': 'mutedpurple',
    '50a747': 'midgreen',
    'a8a495': 'greyish',
    'cfff04': 'neonyellow',
    'ffff7e': 'banana',
    'ff7fa7': 'carnationpink',
    '3c9992': 'sea',
    '886806': 'muddybrown',
    '04f489': 'turquoisegreen',
    'fef69e': 'buff',
    'cfaf7b': 'fawn',
    '3b719f': 'mutedblue',
    'fdc1c5': 'palerose',
    '20c073': 'darkmintgreen',
    '9b5fc0': 'amethyst',
    '0f9b8e': 'blue/green',
    '742802': 'chestnut',
    '9db92c': 'sickgreen',
    'a4bf20': 'pea',
    'cd5909': 'rustyorange',
    'ada587': 'stone',
    'be013c': 'rosered',
    'b8ffeb': 'paleaqua',
    'dc4d01': 'deeporange',
    'a2653e': 'earth',
    '638b27': 'mossygreen',
    '419c03': 'grassygreen',
    'b1ff65': 'palelimegreen',
    '9dbcd4': 'lightgreyblue',
    'fdfdfe': 'palegrey',
    '77ab56': 'asparagus',
    '464196': 'blueberry',
    '990147': 'purplered',
    'befd73': 'palelime',
    '32bf84': 'greenishteal',
    'af6f09': 'caramel',
    'a0025c': 'deepmagenta',
    'ffd8b1': 'lightpeach',
    '7f4e1e': 'milkchocolate',
    'bf9b0c': 'ocher',
    '6ba353': 'offgreen',
    'f075e6': 'purplypink',
    '475f94': 'duskyblue',
    'f5bf03': 'golden',
    'fffeb6': 'lightbeige',
    'fffd74': 'butteryellow',
    '895b7b': 'duskypurple',
    '436bad': 'frenchblue',
    'd0c101': 'uglyyellow',
    'c6f808': 'greenyyellow',
    'f43605': 'orangishred',
    '02c14d': 'shamrockgreen',
    'b25f03': 'orangishbrown',
    '2a7e19': 'treegreen',
    '490648': 'deepviolet',
    '536267': 'gunmetal',
    '5a06ef': 'blue/purple',
    'cf0234': 'cherry',
    '978a84': 'warmgrey',
    '1f0954': 'darkindigo',
    '03012d': 'midnight',
    '2bb179': 'blueygreen',
    'c3909b': 'greypink',
    'a66fb5': 'softpurple',
    '770001': 'blood',
    '922b05': 'brownred',
    '7d7f7c': 'mediumgrey',
    '990f4b': 'berry',
    '8f7303': 'poo',
    'c83cb9': 'purpleypink',
    'acbb0d': 'snot',
    'c071fe': 'easterpurple',
    'ccfd7f': 'lightyellowgreen',
    '00022e': 'darknavyblue',
    '828344': 'drab',
    'ffc5cb': 'lightrose',
    'ab1239': 'rouge',
    'b0054b': 'purplishred',
    '99cc04': 'slimegreen',
    '937c00': 'babypoop',
    '019529': 'irishgreen',
    'ef1de7': 'pink/purple',
    '000435': 'darknavy',
    '42b395': 'greenyblue',
    '9d5783': 'lightplum',
    'c8aca9': 'pinkishgrey',
    'c87606': 'dirtyorange',
    'aa2704': 'rustred',
    'e4cbff': 'palelilac',
    'fa4224': 'orangeyred',
    '0804f9': 'primaryblue',
    '5cb200': 'kermitgreen',
    '76424e': 'brownishpurple',
    '6c7a0e': 'murkygreen',
    '2a0134': 'verydarkpurple',
    '044a05': 'bottlegreen',
    'fd4659': 'watermelon',
    'fe0002': 'fireenginered',
    'cb9d06': 'yellowochre',
    'fb7d07': 'pumpkinorange',
    'b9cc81': 'paleolive',
    'edc8ff': 'lightlilac',
    '61e160': 'lightishgreen',
    '8ab8fe': 'carolinablue',
    '920a4e': 'mulberry',
    'fe02a2': 'shockingpink',
    '9a3001': 'auburn',
    '65fe08': 'brightlimegreen',
    'befdb7': 'celadon',
    'b17261': 'pinkishbrown',
    '885f01': 'poobrown',
    '02ccfe': 'brightskyblue',
    'c1fd95': 'celery',
    '836539': 'dirtbrown',
    'fb2943': 'strawberry',
    '84b701': 'darklime',
    'b66325': 'copper',
    '7f5112': 'mediumbrown',
    '5fa052': 'mutedgreen',
    '6dedfd': "robin'segg",
    '0bf9ea': 'brightaqua',
    'c760ff': 'brightlavender',
    'f6cefc': 'verylightpurple',
    '155084': 'lightnavy',
    'f5054f': 'pinkred',
    '645403': 'olivebrown',
    '7a5901': 'poopbrown',
    'a8b504': 'mustardgreen',
    '3d9973': 'oceangreen',
    '000133': 'verydarkblue',
    '76a973': 'dustygreen',
    '2e5a88': 'lightnavyblue',
    '0bf77d': 'mintygreen',
    'bd6c48': 'adobe',
    'ac1db8': 'barney',
    '2baf6a': 'jadegreen',
    '26f7fd': 'brightlightblue',
    'aefd6c': 'lightlime',
    'ffad01': 'orangeyellow',
    'c69c04': 'ocre',
    'f4d054': 'maize',
    'de9dac': 'fadedpink',
    '05480d': 'britishracinggreen',
    'c9ae74': 'sandstone',
    '60460f': 'mudbrown',
    '8af1fe': 'robineggblue',
    'fdb0c0': 'softpink',
    'b16002': 'orangeybrown',
    'f7022a': 'cherryred',
    'd5ab09': 'burntyellow',
    '86775f': 'brownishgrey',
    'c69f59': 'camel',
    '7a687f': 'purplishgrey',
    '042e60': 'marine',
    'c88d94': 'greyishpink',
    'fffe71': 'pastelyellow',
    '6241c7': 'blueypurple',
    'fffe40': 'canaryyellow',
    'd3494e': 'fadedred',
    '985e2b': 'sepia',
    'a6814c': 'coffee',
    'ff08e8': 'brightmagenta',
    '9d7651': 'mocha',
    'feffca': 'ecru',
    '98568d': 'purpleish',
    '9e003a': 'cranberry',
    '287c37': 'darkishgreen',
    'b96902': 'brownorange',
    'ba6873': 'duskyrose',
    'ff7855': 'melon',
    '94b21c': 'sicklygreen',
    '661aee': 'purplyblue',
    '6140ef': 'purpleishblue',
    '9be5aa': 'hospitalgreen',
    '7b5804': 'shitbrown',
    '276ab3': 'midblue',
    'feb308': 'amber',
    '8cfd7e': 'eastergreen',
    '6488ea': 'softblue',
    '056eee': 'ceruleanblue',
    'b27a01': 'goldenbrown',
    '0ffef9': 'brightturquoise',
    'fa2a55': 'redpink',
    '820747': 'redpurple',
    '7a6a4f': 'greyishbrown',
    'f4320c': 'vermillion',
    'a13905': 'russet',
    '6f828a': 'steelgrey',
    'a55af4': 'lighterpurple',
    'ad0afd': 'brightviolet',
    '004577': 'prussianblue',
    '658d6d': 'slategreen',
    'ca7b80': 'dirtypink',
    '005249': 'darkbluegreen',
    '2b5d34': 'pine',
    'bff128': 'yellowygreen',
    'b59410': 'darkgold',
    '2976bb': 'bluish',
    '014182': 'darkishblue',
    'bb3f3f': 'dullred',
    'fc2647': 'pinkyred',
    'a87900': 'bronze',
    '82cbb2': 'paleteal',
    '667c3e': 'militarygreen',
    'fe46a5': 'barbiepink',
    '94a617': 'peasoupgreen',
    'a88905': 'darkmustard',
    '7f5f00': 'shit',
    '062e03': 'verydarkgreen',
    '8a6e45': 'dirt',
    'cc7a8b': 'duskypink',
    '9e0168': 'redviolet',
    'fdff38': 'lemonyellow',
    'c0fa8b': 'pistachio',
    'eedc5b': 'dullyellow',
    '7ebd01': 'darklimegreen',
    '3b5b92': 'denimblue',
    '01889f': 'tealblue',
    '3d7afd': 'lightishblue',
    '5f34e7': 'purpleyblue',
    '6d5acf': 'lightindigo',
    '748500': 'swampgreen',
    '706c11': 'browngreen',
    '3c0008': 'darkmaroon',
    'cb00f5': 'hotpurple',
    '002d04': 'darkforestgreen',
    '658cbb': 'fadedblue',
    '749551': 'drabgreen',
    'b9ff66': 'lightlimegreen',
    '9dc100': 'snotgreen',
    'faee66': 'yellowish',
    '7efbb3': 'lightbluegreen',
    '7b002c': 'bordeaux',
    'c292a1': 'lightmauve',
    '017b92': 'ocean',
    'fcc006': 'marigold',
    '657432': 'muddygreen',
    'd8863b': 'dullorange',
    '738595': 'steel',
    'aa23ff': 'electricpurple',
    '08ff08': 'fluorescentgreen',
    '9b7a01': 'yellowishbrown',
    'f29e8e': 'blush',
    '6fc276': 'softgreen',
    'ff5b00': 'brightorange',
    'fdff52': 'lemon',
    '866f85': 'purplegrey',
    '8ffe09': 'acidgreen',
    'eecffe': 'palelavender',
    '510ac9': 'violetblue',
    '4f9153': 'lightforestgreen',
    '9f2305': 'burntred',
    '728639': 'khakigreen',
    'de0c62': 'cerise',
    '916e99': 'fadedpurple',
    'ffb16d': 'apricot',
    '7f7053': 'greybrown',
    '77926f': 'greengrey',
    '010fcc': 'trueblue',
    'ceaefa': 'paleviolet',
    '8f99fb': 'periwinkleblue',
    '5539cc': 'blurple',
    '544e03': 'greenbrown',
    '137e6d': 'bluegreen',
    '01f9c6': 'brightteal',
    'c9b003': 'brownishyellow',
    '929901': 'peasoup',
    '0b5509': 'forest',
    'a00498': 'barneypurple',
    '2000b1': 'ultramarine',
    '94568c': 'purplish',
    'c2be0e': 'pukeyellow',
    '748b97': 'bluishgrey',
    '665fd1': 'darkperiwinkle',
    '9c6da5': 'darklilac',
    'c44240': 'reddish',
    'a24857': 'lightmaroon',
    '825f87': 'dustypurple',
    'ca6641': 'terracotta',
    '90b134': 'avocado',
    '01386a': 'marineblue',
    '25a36f': 'tealgreen',
    '75fd63': 'lightergreen',
    '21fc0d': 'electricgreen',
    '5a86ad': 'dustyblue',
    'fec615': 'goldenyellow',
    'fffd01': 'brightyellow',
    'dfc5fe': 'lightlavender',
    'b26400': 'umber',
    '7f5e00': 'poop',
    'de7e5d': 'darkpeach',
    '048243': 'junglegreen',
    '3b638c': 'denim',
    'b79400': 'yellowbrown',
    '84597e': 'dullpurple',
    '411900': 'chocolatebrown',
    '7b0323': 'winered',
    '04d9ff': 'neonblue',
    '667e2c': 'dirtygreen',
    'fbeeac': 'lighttan',
    'd7fffe': 'iceblue',
    '874c62': 'darkmauve',
    'd5ffff': 'verylightblue',
    '826d8c': 'greypurple',
    'ffbacd': 'pastelpink',
    'd1ffbd': 'verylightgreen',
    '448ee4': 'darkskyblue',
    '05472a': 'evergreen',
    'd5869d': 'dullpink',
    '3d0734': 'aubergine',
    '4a0100': 'mahogany',
    'f8481c': 'reddishorange',
    '02590f': 'deepgreen',
    '89a203': 'vomitgreen',
    'e03fd8': 'purplepink',
    'd58a94': 'dustypink',
    '7bb274': 'fadedgreen',
    '526525': 'camogreen',
    'c94cbe': 'pinkypurple',
    'db4bda': 'pinkpurple',
    '9e3623': 'brownishred',
    'b5485d': 'darkrose',
    '735c12': 'mud',
    '9c6d57': 'brownish',
    '028f1e': 'emeraldgreen',
    'b1916e': 'palebrown',
    '49759c': 'dullblue',
    'a0450e': 'burntumber',
    '39ad48': 'mediumgreen',
    'b66a50': 'clay',
    '8cffdb': 'lightaqua',
    'a4be5c': 'lightolivegreen',
    'cb7723': 'brownishorange',
    '05696b': 'darkaqua',
    'ce5dae': 'purplishpink',
    '96ae8d': 'greenishgrey',
    '1fa774': 'jade',
    '7a9703': 'uglygreen',
    'ac9362': 'darkbeige',
    '01a049': 'emerald',
    'd9544d': 'palered',
    'fa5ff7': 'lightmagenta',
    '82cafc': 'sky',
    'fcb001': 'yelloworange',
    '910951': 'reddishpurple',
    'fe2c54': 'reddishpink',
    'cdc50a': 'dirtyyellow',
    '9a0200': 'deepred',
    'be6400': 'orangebrown',
    '030aa7': 'cobaltblue',
    'fe019a': 'neonpink',
    'f7879a': 'rosepink',
    '887191': 'greyishpurple',
    'b00149': 'raspberry',
    '12e193': 'aquagreen',
    'fe7b7c': 'salmonpink',
    'ff9408': 'tangerine',
    '6a6e09': 'brownishgreen',
    '8b2e16': 'redbrown',
    '696112': 'greenishbrown',
    'e17701': 'pumpkin',
    '0a481e': 'pinegreen',
    '343837': 'charcoal',
    'ffb7ce': 'babypink',
    '6a79f7': 'cornflower',
    '82a67d': 'greyishgreen',
    'be0119': 'scarlet',
    '373e02': 'darkolive',
    'caa0ff': 'pastelpurple',
    '02d8e9': 'aquablue',
    '88b378': 'sagegreen',
    '980002': 'bloodred',
    '5cac2d': 'grass',
    '769958': 'moss',
    'a2bffe': 'pastelblue',
    '10a674': 'bluishgreen',
    'af884a': 'darktan',
    '0b8b87': 'greenishblue',
    'ffa756': 'paleorange',
    'a2a415': 'vomit',
    '154406': 'forrestgreen',
    '856798': 'darklavender',
    '632de9': 'purpleblue',
    'd46a7e': 'pinkish',
    '1e488f': 'cobalt',
    'bc13fe': 'neonpurple',
    '7ef4cc': 'lightturquoise',
    '76cd26': 'applegreen',
    '74a662': 'dullgreen',
    '80013f': 'wine',
    'ffffe4': 'offwhite',
    '0652ff': 'electricblue',
    '5729ce': 'bluepurple',
    'ff000d': 'brightred',
    'f10c45': 'pinkishred',
    'acbf69': 'lightolive',
    '6c3461': 'grape',
    '5e819d': 'greyishblue',
    '601ef9': 'purplishblue',
    'b0dd16': 'yellowishgreen',
    'cdfd02': 'greenishyellow',
    'c0737a': 'dustyrose',
    'd6b4fc': 'lightviolet',
    '703be7': 'bluishpurple',
    'fd3c06': 'redorange',
    '40a368': 'greenish',
    '03719c': 'oceanblue',
    'ffffc2': 'cream',
    '7f2b0a': 'reddishbrown',
    'b04e0f': 'burntsienna',
    'a03623': 'brick',
    '87ae73': 'sage',
    '789b73': 'greygreen',
    '98eff9': "robin'seggblue",
    '658b38': 'mossgreen',
    '380835': 'eggplant',
    '5ca904': 'leafgreen',
    'a5a502': 'puke',
    'd648d7': 'pinkishpurple',
    '047495': 'seablue',
    'b790d4': 'palepurple',
    '0b4008': 'huntergreen',
    'ed0dd9': 'fuchsia',
    'ffff84': 'paleyellow',
    'bf9005': 'ochre',
    'd2bd0a': 'mustardyellow',
    'ff474c': 'lightred',
    '0485d1': 'cerulean',
    'ffcfdc': 'palepink',
    '040273': 'deepblue',
    'a83c09': 'rust',
    '90e4c1': 'lightteal',
    '516572': 'slate',
    'd5b60a': 'darkyellow',
    '4b5d16': 'armygreen',
    '80f9ad': 'seafoam',
    'a57e52': 'puce',
    'e2ca76': 'sand',
    'b0ff9d': 'pastelgreen',
    '9ffeb0': 'mint',
    'fdaa48': 'lightorange',
    'fe01b1': 'brightpink',
    '36013f': 'deeppurple',
    '341c02': 'darkbrown',
    'b9a281': 'taupe',
    '8eab12': 'peagreen',
    '9aae07': 'pukegreen',
    '02ab2e': 'kellygreen',
    '7af9ab': 'seafoamgreen',
    '610023': 'burgundy',
    '014d4e': 'darkteal',
    '8f1402': 'brickred',
    '4b006e': 'royalpurple',
    '8fff9f': 'mintgreen',
    'a2cffe': 'babyblue',
    'be03fd': 'brightpurple',
    'd0fefe': 'paleblue',
    '3f9b0b': 'grassgreen',
    'c04e01': 'burntorange',
    '0cff0c': 'neongreen',
    '0165fc': 'brightblue',
    'cf6275': 'rose',
    'ceb301': 'mustard',
    '8e82fe': 'periwinkle',
    'cb416b': 'darkpink',
    '677a04': 'olivegreen',
    'ffb07c': 'peach',
    'ad8150': 'lightbrown',
    'cea2fd': 'lilac',
    '001146': 'navyblue',
    '01ff07': 'brightgreen',
    '35063e': 'darkpurple',
    'ae7181': 'mauve',
    '13eac9': 'aqua',
    'bf77f6': 'lightpurple'
}
color_to_hex = {v: k for k, v in hex_to_color.items()}
assert len(hex_to_color) == len(color_to_hex)


def load_font() -> Dict[str, List[List[bool]]]:
    img = Image.open('font.png')
    chars = (' #\'/'
             '0123456789'
             'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
             'abcdefghijklmnopqrstuvwxyz')
    letters = {}

    for i, ch in enumerate(chars):
        col = 0
        empty_cols = 0
        letter = [[] for _ in range(8)]

        while empty_cols < 2:
            empty_col = True

            for row in range(8):
                color, *_ = img.getpixel((8*i + col, row))
                empty = bool(color)
                empty_col &= empty
                letter[row].append(not empty)

            col += 1

            if empty_col:
                empty_cols += 1
            else:
                empty_cols = 0

        letters[ch] = letter

    return letters


font = load_font()
